#spring:
#  application:
#    name: order-service
#    
#server:
#  port: 8201
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:2001/eureka

#高可用
spring:
  application:
    name: order-service

  rabbitmq:
    host: 192.168.142.135
    port: 5672
    username: admin
    password: admin

  cloud:
    config:
      override-none: true

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
    
###################
feign:
  hystrix:
   enabled: true


#######################################
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#    
#server:
#  port: 8201
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
---
spring:
  profiles: order1
  
server:
  port: 8201   
---
spring:
  profiles: order2
server:
  port: 8202

      

